apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: app-service-blue
spec:
  selector:
    app: app
    version: blue
  ports:
  - name: http
    port: {{ .Values.app.port }}
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: app-service-red
spec:
  selector:
    app: app
    version: red
  ports:
  - name: http
    port: {{ .Values.app.port }}
    protocol: TCP
