apiVersion: v1
kind: Service
metadata:
  name: app-svc-np-blue
spec:
  selector:
    app: app
    version: blue
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.appBlue.port }}
      protocol: TCP
      targetPort: {{ .Values.appBlue.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: app-svc-np-red
spec:
  selector:
    app: app
    version: red
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.appRed.port }}
      protocol: TCP
      targetPort: {{ .Values.appRed.port }}
