apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: app-svc-np-blue
spec:
  selector:
    app: app
    version: blue
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: app-svc-np-red
spec:
  selector:
    app: app
    version: red
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
