name: Docker Image CI - Build & Test

on:
  push:
    branches: [ "dev-test" ]

jobs:
  Code-Checkout-Analysis:
    runs-on: [ ubuntu-latest ]
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    # Step 2: Determine the semantic version
    - name: Determine Version
      id: get_version
      run: |
        # Use release tag if available, else use branch name + short SHA
        echo "Extracting version from commit message"
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "Commit message: $COMMIT_MSG"
        if [[ "$COMMIT_MSG" =~ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
          VERSION="${BASH_REMATCH[0]}"
        else
          VERSION="${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    # Step 3: Run SonarQube code scanner
    - name: SonarQube code scanner
      uses: sonarsource/sonarqube-scan-action@v3
      continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # Step 4: Build the Docker images with semantic version
    - name: Build Blue Docker Image
      run: docker build "blue deployment" --file "blue deployment/Dockerfile" --tag docker.io/udii05/colorflux-blue:${{ env.VERSION }}

    - name: Build Red Docker Image
      run: docker build "red deployment" --file "red deployment/Dockerfile" --tag docker.io/udii05/colorflux-red:${{ env.VERSION }}

    # Step 5: Run Trivy image vulnerability scanner
    - name: Run Trivy Image Scan
      continue-on-error: true
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy \
          --format table \
          image udii05/colorflux-blue:${{ env.VERSION }}
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy \
          --format table \
          image udii05/colorflux-red:${{ env.VERSION }}
    
    # Step 6: Deploy the Docker images to test containers
    - name: Deploy Docker Images to Test Containers
      run: |
        docker stop colorflux-blue-test || true
        docker rm colorflux-blue-test || true
        docker run --rm -d --name colorflux-blue-test -p 8090:80 udii05/colorflux-blue:${{ env.VERSION }}
        docker stop colorflux-red-test || true
        docker rm colorflux-red-test || true
        docker run --rm -d --name colorflux-red-test -p 8091:80 udii05/colorflux-red:${{ env.VERSION }}

    # Step 7: Verify the webpages are accessible
    - name: Check Webpage Accessibility
      run: |
        for i in {1..5}; do
          if curl -s http://localhost:8090 | grep -q "<h1>ColorFlux — DevOps Project</h1>" && curl -s http://localhost:8091 | grep -q "<h1>ColorFlux — DevOps Project</h1>"; then
              echo ""
              echo "SUCCESS! Both webpages are accessible and contain the required header 'ColorFlux — DevOps Project'!"
              exit 0
          else
              echo "Waiting for the webpages with the required header to become accessible..."
              sleep 5
          fi
        done
        echo "ERROR! Webpages are not accessible after waiting!" >&2
        exit 1

    # Step 8: Clean up the Docker containers and images
    - name: Clean up
      run: |
        docker stop colorflux-blue-test || true
        docker rm colorflux-blue-test || true
        docker stop colorflux-red-test || true
        docker rm colorflux-red-test || true
        docker rmi docker.io/udii05/colorflux-blue:${{ env.VERSION }} || true
        docker rmi docker.io/udii05/colorflux-red:${{ env.VERSION }} || true